baseURL = "https://laurancelin.github.io/"
theme = "LoveIt"
title = "Laurance Lin"

defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
hasCJKLanguage = false

copyright = ""  # copyright description used only for SEO schema

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""  # you can add extra information before the name (HTML format is supported), such as icons
    post = "" # you can add extra information after the name (HTML format is supported), such as icons
    name = "Posts"
    url = "/posts/"
    title = ""  # title will be shown when you hover on this menu link

  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""

  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

[params]
  defaultTheme = "auto" # site default theme ["auto", "light", "dark"]
  gitRepo = "https://github.com/LauranceLin/laurancelin.github.io"
  fingerprint = ""  # which hash function used for SRI, when empty, no SRI is used
                    # ["sha256", "sha384", "sha512", "md5"]
  dateFormat = "2006-01-02"
  title = "Laurance Chih-Hsiang Lin"  # website title for Open Graph and Twitter Cards
  description = "Laurance Chih-Hsiang Lin's homepage" # website description for RSS, SEO, Open Graph and Twitter Cards
  images = ["/logo.png"]  # website images for Open Graph and Twitter Cards

  [params.author]
    name = "Laurance C. Lin"
    email = ""
    link = ""

  [params.header]
    desktopMode = "fixed" # desktop header mode ["fixed", "normal", "auto"]
    mobileMode = "auto" # mobile header mode ["fixed", "normal", "auto"]

    [params.header.title]
      logo = ""
      name = "Laurance Lin"
      pre = "" # you can add extra information before the name (HTML format is supported), such as icons
      post = "" # you can add extra information after the name (HTML format is supported), such as icons
      typeit = false  # whether to use typeit animation for title name

  [params.footer]
    enable = true
    custom = "" # Custom content (HTML format is supported)
    hugo = false 
    copyright = true
    author = true
    since = 2025
    icp = ""  # ICP info only in China (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 10 # special amount of posts in each section page
    dateFormat = "01-02"
    rss = 10  # amount of RSS pages

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Laurance C. Lin"
    noFavicon = false
    svgFavicon = "" # modern SVG favicon to use in place of older style .png and .ico files
    themeColor = "#ffffff"  # Android browser theme color
    iconColor = "#5bbad5" # Safari mask icon color
    tileColor = "#da532c" # Windows v8-11 tile color

  [params.search]
    enable = true
    type = "algolia"  # type of search engine ["lunr", "algolia"]
    contentLength = 4000  # max index length of the chunked content
    placeholder = "Search"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "strong"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.png"
      title = "Laurance Chih-Hsiang Lin"
      subtitle = "Information Technology | Business Economics | Quantitative Finance"
      typeit = true # whether to use typeit animation for subtitle
      social = true # whether to show social links
      disclaimer = ""

    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = ""
    Linkedin = ""
    # Facebook = ""
    Medium = ""
    # Youtubechannel = ""
    # Stackoverflow = ""
    # Discord = ""
    Email = ""

  [params.page]
    hiddenFromHomePage = false  # whether to hide a page from home page
    hiddenFromSearch = false  # whether to hide a page from search results
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false

    [params.page.toc]
      enable = true
      keepStatic = false  # whether to keep the static table of the contents in front of the post
      auto = true # whether to make the table of the contents in the sidebar automatically collapsed

    [params.page.code]
      copy = true
      maxShownLines = 20
      [params.page.code.render]
        goat = true
        mermaid = true
    
    [params.page.math]  # KaTeX mathematical formulas config (KaTeX https://katex.org/)
      enable = false
      # default inline delimiter is $ ... $ and \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
   
    [params.page.mapbox]   # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    [params.page.share]
      enable = true
      X = true
      Threads = true
      Facebook = true
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = false
      Mix = false
      Telegram = true

    [params.page.comment]
      enable = true

      [params.page.comment.disqus]  # Disqus comment config (https://disqus.com/)
        enable = false
        shortname = "" 
      
      [params.page.comment.gitalk]  # Gitalk comment config (https://github.com/gitalk/gitalk)
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      
      [params.page.comment.valine]  # Valine comment config (https://github.com/xCss/Valine)
        enable = true
        appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
        appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        # automatically adapt the current theme i18n configuration when empty
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # emoji data file name, default is "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # located in "themes/LoveIt/assets/lib/valine/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/lib/valine/emoji/"
        emoji = ""
      
      [params.page.comment.facebook]  # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        # automatically adapt the current theme i18n configuration when empty
        languageCode = ""
      
      [params.page.comment.telegram]  # Telegram comments config (https://comments.app/)
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      
      [params.page.comment.commento]  # Commento comment config (https://commento.io/)
        enable = false
      
      [params.page.comment.utterances]  # utterances comment config (https://utteranc.es/)
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      
      [params.page.comment.giscus]  # giscus comment config (https://giscus.app/)
        # You can refer to the official documentation of giscus to use the following configuration.
        enable = false
        repo = ""
        repoId = ""
        category = "Announcements"
        categoryId = ""
        # automatically adapt the current theme i18n configuration when empty
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
      
      [params.page.comment.waline]  # Waline comment config (https://waline.js.org/)
        enable = false
        serverURL = ""
        # automatically adapt the current theme i18n configuration when empty
        lang = ""
        emoji = ["https://unpkg.com/@waline/emojis@1.0.1/tw-emoji"]
    
    [params.page.library] # Third-party library config
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" 位于 "assets/"
        # Or
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" 位于 "assets/"
        # Or
        # someJavascript = "https://cdn.example.com/some.js"

    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = "Laurance Chih-Hsiang Lin"
        logoUrl = ""

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1   # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)

  [params.verification] # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  [params.seo]
    image = ""
    thumbnailUrl = ""

  [params.analytics]
    [params.analytics.google] # Google Analytics
      id = ""
      respectDoNotTrack = false
    
    [params.analytics.fathom] # Fathom Analytics
      id = ""
      server = "" # server url for your tracker if you're self hosting
    
    [params.analytics.plausible]  # Plausible Analytics
      dataDomain = ""
    
    [params.analytics.yandexMetrica]  # Yandex Metrica
      id = ""

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]  # text strings used for Cookie consent banner
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

  [params.compatibility]
    polyfill = false  # whether to use Polyfill.io to be compatible with older browsers
    objectFit = false # whether to use object-fit-images to be compatible with older browsers

[markup]
  [markup.highlight]  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
  
  [markup.goldmark] # Goldmark is from Hugo 0.60 the default library used for Markdown
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true # whether to use HTML tags directly in the document

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

[privacy]
  # privacy of the Google Analytics (can also be configured in params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    # ...
  [privacy.youtube]
    # ...

[mediaTypes]  # Options to make output .md files
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]  # Options to make output .md files
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs] # Options to make hugo output files
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
    [languages.en.params]
      [languages.en.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = "Search"
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [languages.en.params.search.algolia]
          index = ""
          appID = ""
          searchKey = ""
      [languages.en.params.home]
        rss = 10
        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.png"
          title = "Laurance C. Lin"
          subtitle = "Information Technology | Business Economics | Quantitative Finance"
          typeit = true
          social = true
          disclaimer = ""
      [languages.en.params.social]
        GitHub = "LauranceLin"
        Linkedin = "LauranceLin"
        Medium = "laurance0410"
        Email = "b11705050@ntu.edu.tw"
        RSS = true

  [languages.zh-tw]
    weight = 2
    languageCode = "zh-TW"
    languageName = "中文"
    hasCJKLanguage = true
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.zh-tw.menu]
      [[languages.zh-tw.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "所有文章"
        url = "/posts/"
        title = ""
      [[languages.zh-tw.menu.main]]
        weight = 2
        identifier = "categories"
        pre = ""
        post = ""
        name = "類別"
        url = "/categories/"
        title = ""
      [[languages.zh-tw.menu.main]]
        weight = 3
        identifier = "about"
        pre = ""
        post = ""
        name = "關於"
        url = "/about/"
        title = ""
    [languages.zh-tw.params]
      [languages.zh-tw.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = "搜尋"
        maxResultLength = 10
        snippetLength = 50
        highlightTag = "em"
        absoluteURL = false
        [languages.zh-tw.params.search.algolia]
          index = ""
          appID = ""
          searchKey = ""
      [languages.zh-tw.params.home]
        rss = 10
        [languages.zh-tw.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.png"
          title = "Laurance C. Lin"
          subtitle = "資訊科技 | 商業經濟 | 量化金融"
          typeit = true
          social = true
          disclaimer = ""
      [languages.zh-tw.params.social]
        GitHub = "LauranceLin"
        Linkedin = "LauranceLin"
        Medium = "laurance0410"
        Email = "b11705050@ntu.edu.tw"
        RSS = true